const statData = [
  {
    year: "2021",
    games: "4 (WR)",
    receptions: "9 (14 tgts)",
    receivingYards: "175 (19.4 ypr)",
    targetShare: "3.4%",
    catchRate: "64.3%",
    receivingTDs: 2,
    specialTeamsYards: 0,
    age: 18,
    school: "Oregon",
  },
  {
    year: "2022",
    games: "10 (WR)",
    receptions: "17 (24 tgts)",
    receivingYards: "366 (21.5 ypr)",
    targetShare: "5.6%",
    catchRate: "70.8%",
    receivingTDs: 1,
    specialTeamsYards: 0,
    age: 19,
    school: "Oregon",
  },
  {
    year: "2023",
    games: "6 (WR)",
    receptions: "13 (23 tgts)",
    receivingYards: "224 (17.2 ypr)",
    targetShare: "5.6%",
    catchRate: "56.5%",
    receivingTDs: 1,
    specialTeamsYards: 0,
    age: 20,
    school: "Tennessee",
  },
  {
    year: "2024",
    games: "11 (WR)",
    receptions: "26 (34 tgts)",
    receivingYards: "661 (25.4 ypr)",
    targetShare: "9.1%",
    catchRate: "76.5%",
    receivingTDs: 6,
    specialTeamsYards: 0,
    age: 21,
    school: "Tennessee",
  },
];

export default statData;
